Remove LF2.createLoanToken()
trusttoken/smart-contracts pull request #1015
Opened 2021-09-30 12:55 UTC by MaciejNadolski98

2021-09-30 22:24 UTC, yuchenlintt requested changes

2021-09-30 22:24 UTC, yuchenlintt commented on contracts/truefi2/LoanFactory2.sol
>      function createFTLALoanToken(
The only callers of `_createFTLALoanToken()` were `createLoanToken()`, and `createFTLALoanToken()`, so now we can collapse this into a single function.

2021-09-30 22:24 UTC, yuchenlintt commented on test/integration/TrueLender2.test.ts
> +xdescribe('TrueLender2', () => {
We should migrate integration tests to FTLA. Mikolaj already filed a follow-up task for his PR, so no further action required.

2021-10-01 14:08 UTC, yuchenlintt approved these changes

2021-10-01 15:08 UTC, skalermo approved these changes

2021-10-01 15:13 UTC, merged