✅ Add minimal BorrowingMutex formal verification
trusttoken/smart-contracts pull request #1101
Opened 2021-10-30 14:52 UTC by MaciejNadolski98

2021-10-30 14:56 UTC, MaciejNadolski98 commented on .gitignore
> +.last_confs
Certora doesn't seem to provide a way to create those files elsewhere out-of-the-box, so they will be ignored for now

2021-10-30 14:58 UTC, MaciejNadolski98 commented on spec/truefi2/BorrowingMutex.spec
> +rule onePlusTwoEqualsThree(uint one, uint two) {
This is left from previous commit for sake of an example, will be removed later.

2021-11-01 14:39 UTC, yuchenlintt requested changes
Hooray for Certora access!

Until we hook this up to CircleCI, let's establish a coding convention of adding a PR comment that links to the most recent verification report (for modified spec files), after every commit that's ready for review. I haven't had a chance to run this spec myself yet, but when I do I'll attach the verification report.

And don't forget to track tasks on our board :) I suppose I should be _adding_ tasks to our board as well.

2021-11-01 14:39 UTC, yuchenlintt commented on spec/truefi2/BorrowingMutex.spec
> +rule unlockedIntoBanned() {
Correct me if I'm mistaken, but I believe this rule currently says (in pseudocode)
```
(in a reasonable environment with an unlocked borrower)
if anyone calls lock:
  (with a reasonable locker)
  then borrower is not banned
else:
  any other successful function call won't ban borrower either
```

If so, then let's:
1. simplify this rule so it only verifies a single simple proof. We could use a `require(f.selector == ...)` instead of branching with an if block, so this rule would only be concerned with function calls to `lock()`.
2. give the rule a more descriptive name, like `reasonableLocksDoNotBanUnlockedBorrowers()`. A Certora convention appears to be writing rules as [declarative statements](https://prover.certora.com/output/92911/ad05c881e7b59c4af535/?anonymousKey=a03aa9ba4d959b530c5cbd427350385bf8a5e22a#envfreeFuncsAreNonpayableResults). I'm not sure whether we should make the subject of the sentence singular or plural though. (In a typical unit test, the subject would of course be singular because we're only traveling one path through code, but here we're proving _all_ subjects follow a rule.)
3. separately create other simple rules around banning, like `onlyBansOrLocksCanBanBorrower`, or `bannedBorrowersCannotBeReasonablyUnbanned()` (might be _too_ verbose? I'd be okay with dropping `Reasonably`). We should do this in separate PRs, since the purpose of this PR is to check in a proof of concept and establish coding conventions.

2021-11-02 11:53 UTC, MaciejNadolski98 commented on spec/truefi2/BorrowingMutex.spec
> +rule unlockedIntoBanned() {
The interpretation is correct, although the goal of this rule is to make sure that it's impossible to go from unlocked to banned directly, no matter what function was called exactly - it's more of a rule about possible transitions between states rather than a test of how a function affects the states
1. The `if` statement specialises locker address assumption for `lock()` call. I think this is a good presentation of how that can be done without sacrificing generality and would leave it in as is.
2. Takeaways:
- use declarative statements as rule names
- drop "reasonable". (unless we wanted to differentiate between function with open access and onlyOwner access)
- i would stick to singular, my reasoning is "(any reasonable call to a)functionDoesNotBanUnlockedBorrower"
- additionally I would consider adding comments pointing out non-trivial assumptions (it's obvious that the `msg.sender` is not going to be address(1), but a `locker` function argument could be). Certora translates their rules to Hoare triples in Audit reports, we could mimic that in some form of documentation. (added as task)
3. Agree, add more rules in a following PR.

2021-11-02 12:05 UTC, MaciejNadolski98 commented on spec/truefi2/BorrowingMutex.spec
> +methods {
Verification report:
https://prover.certora.com/output/67403/1e4853bceba0c7cd83c7/?anonymousKey=7a9f73737871b861a55ebcabad823860de344431

2021-11-02 17:20 UTC, yuchenlintt commented on spec/truefi2/BorrowingMutex.spec
> +    if (f.selector == lock(address, address).selector) {
Declined. Let's keep as is.

Without currying it's hard to express `require(!(f.selector == foo().selector && args[2] == bar))` constraints, and it ends up being less verbose to use if/else blocks for these.

Another option is to fix `BorrowingMutex` so it reverts when locking to `address(1)` (my preference). Can and should be done in a follow-up PR.

2021-11-02 17:21 UTC, yuchenlintt approved these changes

2021-11-04 10:14 UTC, MiksuJak approved these changes

2021-11-04 10:29 UTC, merged