Fix for rarely failing tests
trusttoken/smart-contracts pull request #419
Opened 2020-12-17 12:56 UTC by MiksuJak

2020-12-17 13:48 UTC, barrutko approved these changes
Imo looks good, but it would be nice if @vanruch could also have a look.

2020-12-17 13:55 UTC, vanruch requested changes
We are mixing two completely different types of measuring closeliness of numbers. What's worse, in one case it gets more precise with growing eps and in another - with declining. I would propose to split it into two different functions: rename `expectCloseTo` to `expectScaledCloseTo` and make `expectCloseTo` a simple check of `a-b`

2020-12-17 14:09 UTC, MiksuJak commented
> We are mixing two completely different types of measuring closeliness of numbers. What's worse, in one case it gets more precise with growing eps and in another - with declining. I would propose to split it into two different functions: rename `expectCloseTo` to `expectScaledCloseTo` and make `expectCloseTo` a simple check of `a-b`

Right, sounds reasonable. Apparently simple check `a-b` does not work for bigger numbers, that's why we need two methods.

2020-12-22 09:58 UTC, vanruch approved these changes

2020-12-22 10:09 UTC, merged