Allow closiong fully repaid loan before term passes
trusttoken/smart-contracts pull request #440
Opened 2021-01-19 12:28 UTC by MiksuJak

2021-01-20 09:58 UTC, barrutko approved these changes

2021-01-20 17:40 UTC, barrutko requested changes
Let's make sure it won't affect TrueRatingAgency rewarding schedule.

2021-03-04 16:33 UTC, hal909 reviewed
- Look into whether this breaks anything that might calculate outside of LoanToken
- Write tests handling edge cases for closing early

2021-03-22 14:42 UTC, barrutko approved these changes

2021-03-23 22:01 UTC, hal909 approved these changes

2021-03-23 22:01 UTC, merged