Make ImplementationReference claimable instead of ownable
trusttoken/smart-contracts pull request #556
Opened 2021-03-30 14:25 UTC by skalermo

2021-03-30 15:12 UTC, vanruch commented
Do we want to use claimable pattern for rest of TrueFi2 contracts?

2021-03-30 15:19 UTC, vanruch approved these changes

2021-03-30 15:32 UTC, vanruch approved these changes

2021-04-01 12:27 UTC, skalermo commented
sure

2021-04-06 20:56 UTC, hal909 requested changes
Let's go ahead with what we discussed in the meeting today. Use UpgradeableClaimable and rename the file to Claimable.sol. This is the claimable contract we will use in all future contracts.

2021-04-07 13:29 UTC, closed without merging