Switch strategies
trusttoken/smart-contracts pull request #562
Opened 2021-04-01 11:06 UTC by skalermo

2021-04-01 13:26 UTC, vanruch commented on contracts/truefi2/TrueFiPool2.sol
> +    event SwitchedStrategy(ITrueStrategy newStrategy);
`StrategySwitched`

2021-04-01 13:32 UTC, vanruch commented on contracts/truefi2/TrueFiPool2.sol
> +        strategy = newStrategy;
Let's get overprotective and call withdrawAll as last thing in the function. Do something like 
```
ITrueStrategy previousStrategy = strategy
strategy = newStrategy
```

2021-04-02 20:37 UTC, hal909 requested changes
implement Ivan's feedback

2021-04-06 13:46 UTC, vanruch approved these changes

2021-04-06 13:47 UTC, merged