Make liquidations work with any asset
trusttoken/smart-contracts pull request #599
Opened 2021-04-16 15:57 UTC by MiksuJak

2021-04-18 15:45 UTC, hal909 commented on contracts/truefi2/Liquidator2.sol
> +        ITrueFiPool2 pool = ITrueFiPool2(loan.pool());
check here that loan.token() is on approvedTokens

2021-04-18 15:46 UTC, hal909 commented on contracts/truefi2/Liquidator2.sol
> +        ITrueFiPool2 pool = ITrueFiPool2(loan.pool());
require(approvedLoans(pool.token() != 0), "Liquidator: Token not approved for default protection");

2021-04-18 15:46 UTC, hal909 commented on contracts/truefi2/Liquidator2.sol
> +
Add approved tokens mapping

mapping(address => bool) approvedTokens;

2021-04-18 15:47 UTC, hal909 commented on contracts/truefi2/Liquidator2.sol
> +
Add function setTokenApproval(address _token) onlyOwner which allows setting token approvals in approvedTokens

2021-04-18 15:48 UTC, hal909 commented on contracts/truefi2/Liquidator2.sol
> +        require(loan.status() == ILoanToken2.Status.Defaulted, "Liquidator: Loan must be defaulted");
check-effects: move this require to the beginning of the function before making the withdrawal

2021-04-18 15:49 UTC, hal909 commented on contracts/truefi2/Liquidator2.sol
> +        emit Liquidated(loan);
emit defaultedValue in this event

2021-04-18 15:50 UTC, hal909 commented on contracts/truefi2/Liquidator2.sol
> +    event Liquidated(ILoanToken2 loan);
add uint256 defaultedValue in this event

2021-04-18 15:51 UTC, hal909 commented on contracts/truefi2/Liquidator2.sol
> +        uint256 maxWithdrawValue = stakingPoolSupply.mul(fetchMaxShare).div(10000);
divide by BASIS constant

2021-04-18 15:52 UTC, hal909 commented on contracts/truefi2/Liquidator2.sol
> +        require(newShare <= 10000, "Liquidator: Share cannot be larger than 10000");
check newShare <= BASIS instead of 10000

2021-04-18 15:52 UTC, hal909 commented on contracts/truefi2/Liquidator2.sol
> +
add uint256 constant BASIS = 10000

2021-04-18 15:53 UTC, hal909 requested changes
A few things to change, most importantly adding a whitelist of tokens approved for liquidation. The whitelist should hold the token address (e.g. DAI address) and allow owner to add tokens approved for liquidation.

2021-04-19 12:45 UTC, vanruch commented on contracts/truefi2/Liquidator2.sol
> +    IPoolFactory public poolFactory;
I think poolFactory is unused

2021-04-19 12:51 UTC, vanruch commented on contracts/truefi2/Liquidator2.sol
> +        require(approvedTokens[address(pool.token())] == true, "Liquidator: Token not approved for default protection");
```suggestion
        require(approvedTokens[address(pool.token())], "Liquidator: Token not approved for default protection");
```

2021-04-19 15:44 UTC, hal909 approved these changes

2021-04-19 15:44 UTC, merged