Deploy TrueFi2 on Ropsten
trusttoken/smart-contracts pull request #617
Opened 2021-04-27 14:43 UTC by vanruch

2021-04-27 18:01 UTC, yuchenlintt requested changes
Thanks for rolling out the TrueFi2 deploy!

Two things to address:
- I would prefer the current naming scheme, where Ropsten test contracts are named TestTrustToken, etc. This prevents naming conflicts between deployments.json and Etherscan or other services.
- Could you submit the script that deployed the TrueFi2 addresses as deploy/truefi2.ts?

To clean up this PR a bit, I'll factor out the (minor) style changes into a separate PR, and the testTrueFiPool upgrade in another one.

2021-04-28 09:04 UTC, vanruch commented on deploy/truefi.ts
> +    ? timeProxy(contract('trustToken', TrustToken), 'initialize',
Yeah, I agree, we should keep it as obvious as possible, will undo the change now

2021-04-28 16:56 UTC, yuchenlintt commented
Thanks for adding the `deploy/truefi2.ts` script! Let's merge that file as-is so that the exact script that deployed these contracts is recorded in the commit history, and then follow up with a PR to address structure + style changes. Looks good overall.

Since there is a PR backlog right now, I propose the following merge sequence:
1) Merge #619 and #620 to dev. (These are the PRs factoring out irrelevant changes from this PR.)
2) Merge dev to this PR (#617). Fix any merge conflicts.
3) Revert changes to `deploy/truefi.ts` and `package.json` in this PR.
4) Merge this PR to dev.
5) I'll follow up with a PR to address structure + style changes in `deploy/truefi2.ts`

If this proposal sounds good to you, feel free to approve + merge #619, #620, and #617 even if I'm not awake to grant approval.

2021-04-28 18:01 UTC, hal909 approved these changes

2021-04-28 18:52 UTC, yuchenlintt approved these changes

2021-04-28 18:57 UTC, merged