Make tolerance in the pool smaller
trusttoken/smart-contracts pull request #647
Opened 2021-05-18 13:19 UTC by vanruch

2021-05-18 14:38 UTC, yuchenlintt requested changes
Looks good! Just some minor documentation fixes.

2021-05-18 14:38 UTC, yuchenlintt commented on contracts/truefi2/strategies/CurveYearnStrategy.sol
> +    uint256 public constant MAX_PRICE_SLIPPAGE = 200; // 3%
Don't forget to update the comment: `// 2%`

2021-05-18 14:38 UTC, yuchenlintt commented on contracts/truefi2/TrueFiPool2.sol
> +    // tolerance difference (percents) between
`between expected`

2021-05-18 21:26 UTC, yuchenlintt approved these changes

2021-05-19 05:40 UTC, hal909 approved these changes

2021-05-19 05:40 UTC, merged