Remove unused contracts
trusttoken/smart-contracts pull request #747
Opened 2021-07-07 09:11 UTC by skalermo

2021-07-09 23:22 UTC, yuchenlintt commented
Thanks for taking on this task! Culling zombie code is one of the best things for repo health.

I can't comment on all the deletions, but I know:
- CrvPriceOracle is still used in our CurveYearnStrategy
- SushiTimelock and TruSushiswapRewarder are still used for the Sushiswap farm

Could you split this PR into smaller PRs so it's easier to evaluate on a contract-by-contract basis what we can safely delete?

2021-07-13 10:53 UTC, barrutko commented
I agree with @yuchenlintt. Let's issue multiple smaller PRs, one by one, with a smaller number of removals. For example, let's start with extracting the removal of Avalanche stuff to separate PR.

2021-07-14 21:29 UTC, hal909 commented on contracts/avalanche/AvalancheTokenController.sol
> -// SPDX-License-Identifier: MIT
Keep this file. We still need to maintain Avalanche smart contracts

2021-07-14 21:29 UTC, hal909 commented on contracts/avalanche/AvalancheTrueUSD.sol
> -// SPDX-License-Identifier: MIT
Keep this file.

2021-07-14 21:30 UTC, hal909 commented on contracts/truefi/SushiTimelock.sol
> -// SPDX-License-Identifier: MIT
Keep this file.

2021-07-14 21:30 UTC, hal909 commented on contracts/truefi/TruSushiswapRewarder.sol
> -// SPDX-License-Identifier: MIT
Keep this file

2021-07-14 21:31 UTC, hal909 requested changes
There are some files we need to keep.
1. AvalanceTrueUSD
2. AvalancheTokenController
3. SushiTimeLock
4. SushiSwapRewarder

2021-07-15 15:10 UTC, skalermo commented
Removal of the unused contracts was split into separate PRs #763, #764 and #765 and merged. As for the Avalanche contracts (#763) we will have to restore them. 
I think we can close this PR.

2021-07-15 17:11 UTC, yuchenlintt commented
Apologies about the miscommunication, Hal. We probably should have closed this PR once we split it, to avoid duplicate review work. Closing this now and reverting #763.

2021-07-15 17:11 UTC, closed without merging