Add utilization function
trusttoken/smart-contracts pull request #756
Opened 2021-07-09 08:22 UTC by skalermo

2021-07-09 08:33 UTC, vanruch commented on contracts/truefi2/TrueFiPool2.sol
> +        return poolValue().sub(liquidValue()).mul(BASIS_PRECISION).div(poolValue());
poolValue calculation is expensive, call it only once

2021-07-09 13:35 UTC, yuchenlintt commented
The spec wording is phrased in terms of utilization because that's how the credit team modeled it, but our utilization adjustment is actually calculated using 1 - utilization. I think it would be simpler to make a liquidRatio() function instead of this utilization(), otherwise we'd be spending some extra gas to calculate 1 - (poolValue - liquidValue) / poolValue == liquidValue / poolValue

2021-07-09 13:36 UTC, yuchenlintt requested changes
The spec wording is phrased in terms of utilization because that's how the credit team modeled it, but our utilization adjustment is actually calculated using 1 - utilization. I think it would be simpler to make a liquidRatio() function instead of this utilization(), otherwise we'd be spending some extra gas to calculate 1 - (poolValue - liquidValue) / poolValue == liquidValue / poolValue

2021-07-09 18:45 UTC, vanruch commented
@yuchenlintt Are you sure? When liquidValue = poolValue, utilization is 0% -> rate = 0, when liquidValue = 0 -> utilization = 100%, rate is high. Looks like it should be `(poolValue - liquidValue) / poolValue`

2021-07-09 19:05 UTC, yuchenlintt commented
Yes, I believe I'm correct.

The interest rate adjustment for utilization should asymptotically approach infinity (but capped at 500%) as utilization approaches 100% (discouraging further borrowing and encouraging more lending), and it should approach 0% as utilization approaches 0% (encouraging further borrowing). This gets added to the base rate.

2021-07-12 16:13 UTC, yuchenlintt approved these changes
Thanks for adding `liquidRatio()`!

I don't believe `utilization()` will be used anywhere else, and if it isn't used then I'd prefer to remove it. But this isn't a strong opinion so I'm approving and letting you decide whether to keep it.

2021-07-13 08:38 UTC, merged