Store borrow limits in CreditOracle
trusttoken/smart-contracts pull request #762
Opened 2021-07-12 14:14 UTC by vanruch

2021-07-12 16:09 UTC, yuchenlintt requested changes
Looks good! Could you update naming throughout the PR to match the spec?

2021-07-12 16:09 UTC, yuchenlintt commented on contracts/truefi2/TrueFiCreditOracle.sol
> +    mapping(address => uint256) borrowLimit;
Could you change this to `maxBorrowerLimit` to match the spec? `borrowLimit` by itself could confuse users and give them the impression they could borrow up to that amount.

Also don't forget to update the comment!

2021-07-12 16:09 UTC, yuchenlintt commented on test/truefi2/TrueFiCreditOracle.test.ts
> +    it('only manager can set scores', async () => {
s/score/max borrower limit/g

2021-07-13 07:28 UTC, barrutko commented on contracts/truefi2/TrueFiCreditOracle.sol
> +    // @dev Track credit scores for an account
```suggestion
    // @dev Track max borrowing limit for an account
```

2021-07-13 07:54 UTC, yuchenlintt approved these changes
LGTM, thanks!

2021-07-13 09:45 UTC, MiksuJak approved these changes

2021-07-13 10:51 UTC, merged