Add a check in liquidator/safu, if all of provided loans are of a single borrower
trusttoken/smart-contracts pull request #981
Opened 2021-09-17 12:02 UTC by MiksuJak

2021-09-17 12:21 UTC, yuchenlintt requested changes

2021-09-17 12:21 UTC, yuchenlintt commented on contracts/truefi2/Liquidator2.sol
> +            areLoansOfSingleBorrower(loans),
How about this naming instead?
```suggestion
            allLoansHaveSameBorrower(loans),
```
If you like this, please update the error message text as well.

2021-09-17 12:21 UTC, yuchenlintt commented on contracts/truefi2/Liquidator2.sol
> +        if (loans.length == 1) {
If we pass in an empty list this is vacuously true.
```suggestion
        if (loans.length <= 1) {
```
I think we don't need to revert on empty lists (an empty list shouldn't hurt, it just wastes the caller's gas). But maybe we should add a unit test to confirm an empty list doesn't transfer any TRU.

2021-09-20 09:31 UTC, yuchenlintt approved these changes

2021-09-21 09:52 UTC, skalermo approved these changes

2021-09-21 10:00 UTC, merged