Split deployments.json by network
trusttoken/smart-contracts pull request #985
Opened 2021-09-20 09:19 UTC by MaciejNadolski98

2021-09-20 12:09 UTC, yuchenlintt requested changes
Thanks for the change! I have some preliminary comments attached to this review.

Since this file is such an important piece of our repo, I also recommend we have 3 engineers do a full diff check of the final commit of this PR to confirm all the addresses are identical.

Could you preserve the git blame version history in `deployments-mainnet.json` instead of in `deployments-ropsten.json`? You should be able to achieve this by rewriting this branch in the following sequence:
1. git mv deployments.json deployments-mainnet.json
2. git add, commit, etc.
3. Cut ropsten addresses and paste to deployments-ropsten.json
4. Cut unknown addresses and paste to deployments-unknown.json

2021-09-20 12:24 UTC, yuchenlintt commented on deployments-ropsten.json
> +      "txHash": "0xa646bc5731878a7dbeed46b51b991101ee1fe2bbc7186333c7c4968da525901d",
It looks like this is fixed now. Resolving this comment.

2021-09-21 09:10 UTC, yuchenlintt requested changes
One more change in marsDeploy.sh, otherwise this PR LGTM!

2021-09-21 09:10 UTC, yuchenlintt commented on deployments-mainnet.json
>  {
This file was the most stressful to review, but now it's the easiest! LGTM.

2021-09-21 09:10 UTC, yuchenlintt commented on deployments-ropsten.json
> +{
I'm confirming I diffed this file against the ropsten section of the original deployments.json and found no changes.

2021-09-21 09:10 UTC, yuchenlintt commented on deployments-unknown.json
> +{
I'm confirming I diffed this file against the unknown section of the original deployments.json and found no changes.

2021-09-21 09:50 UTC, yuchenlintt approved these changes

2021-09-21 10:09 UTC, barrutko approved these changes

2021-09-21 10:21 UTC, MiksuJak approved these changes

2021-09-21 10:22 UTC, merged